# Generated by Django 5.0.2 on 2024-02-26 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2024, 2, 26, 18, 32, 17, 488601),
                    ),
                ),
                ("text", models.CharField(max_length=1000000)),
            ],
        ),
    ]
